### PR TITLE
Allow disabling regular miners

### LINKED ISSUE #965: add option of "optionalminers only" (fastest)

### PR DESCRIPTION
**Pull request by grantemsley**
Fixes #965 

Checkbox will disable the regular miners, so you can choose regular, optional, both, or none (which could actually be useful if you have a CustomMiners folder).

### CODE REVIEW

**Comment by sephir69** [comment]
would you be able to implement a feature that allows you to pick the specific ps1 miner files you want to run? atm I just delete the ones out I don't like to run but it gets tedious with updates and fresh installs.

**Comment by grantemsley** [comment]
@sephir69 why do you not want to run them?  If it's because they don't work properly on your system (that's why I do it), I'd rather see #896 resolved first.

**Comment by sephir69** [comment]
yeah some crash and others i already know are slower and would never use

**Comment by nemosminer** [comment]
we could also add a third of option of UserSelectedMiners (customMiners) folder 

this folder would remain empty and unaffected by auto updates 

user have the option of placing any miner.ps1 in that folder and will only run the miner.ps1 they select

**Comment by grantemsley** [comment]
You can do that with this PR already.  Put the miners you want in the CustomMiners folder.  Don't check either of the miner check boxes in the config.  It will only use the ones in the CustomMiners folder then.

Still not terribly useful in this case since most of the updates are to the miners themselves, so you still have to manually sort through which ones you want.  Getting banning of failing miners working properly would be more helpful for that I think.

**Pull request merged**
