### PR TITLE
Official download link for zealot/enemy-1.08

### PR DESCRIPTION
**Pull request by borzaka**
From the original bitcointalk forum: https://bitcointalk.org/index.php?topic=3378390.0

### CODE REVIEW

**Comment by nemosminer** [comment]
thanks but i like auto download urls... you can swap bin files manually if you do not trust me...

**Comment by nemosminer** [comment]
it is but coul;d change at any time... my files are excatly the same just uploaded to my server which i know will stay up and not change urls anytime soon...

**Comment by borzaka** [comment]
It is true for all other miners included in NemosMiner.
I thought you uploaded to your server, because there wasn't an official direct download URL, only a file share link, which can't be direct downloaded without user interaction.

**Comment by nemosminer** [comment]
you thought wrong...

**Pull request closed without merging**
